server:
  port: 10300
spring:
  application:
    name: gateway-zuul
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:10110/eureka
  instance:
    ip-address: true
zuul:
#  ignoredServices: '*'   #忽略所有请求
  routes:
    hystrix:
      path: /hystrix/**
      serviceId: spring-boot-hystrix
      #http://192.168.12.238:10300/spring-boot-hystrix/hystrix/test/query
      #最后就会跳转到spring-boot-hystrix集群上/hystrix/test/query服务
    bootNode:
      path: /node/**
      serviceId: spring-boot-node
      #http://192.168.12.238:10300/spring-boot-node/node/baseInfo/query
      #然后会走eureka的路由功能 默认采用轮训去调用两个节点间