##用于添加权限校验 true为开false为关
security:
  basic:
      #代表开启账号密码认证
    enabled: false
  user:
    name: pan
    password: 123456
server:
  port: 10110
eureka:
  instance:
      #配置服务名
    hostname: localhost
  client:
    service-url:
      #代表注册到eureka服务端的地址
      defaultZone: http://localhost:10110/eureka
    #该服务为注册中心，增加此行代表不在注册中心注册自己
      register-with-eureka: true
      #由于注册中心呢的职责是维护实例，为FALSE代表其不用去检索服务
      fetch-registry: false
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 4000